//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yDashboard2
{
    using System;
    using System.Collections.Generic;
    
    public partial class OlympicAthlete
    {
        public int id { get; set; }
        public string Athlete { get; set; }
        public Nullable<int> Age { get; set; }
        public string Country { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.DateTime> Closing_Ceremony_Date { get; set; }
        public string Sport { get; set; }
        public Nullable<int> Gold_Medals { get; set; }
        public Nullable<int> Silver_Medals { get; set; }
        public Nullable<int> Bronze_Medals { get; set; }
        public Nullable<int> Total_Medals { get; set; }
    }
}
